plugins {
    id 'com.android.application'
}

android {
    namespace 'com.adnani.nawawi42'
    compileSdk 35

    defaultConfig {
        applicationId 'com.adnani.nawawi42'
        minSdk 19
        targetSdk 35
        versionCode 1
        versionName '0.1.0-test001'
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
